[2024-12-28 23:38:16,907] INFO serviceapp.serializers User with phone=+79990000000 found (id=1), updating data.
[2024-12-28 23:38:16,910] DEBUG serviceapp.amocrm_client Searching contacts with params: {'page': 1, 'limit': 50, 'filter': '[{"field": "744499", "operator": "EQUALS", "value": "clientlogin1"}]'}
[2024-12-28 23:38:17,441] ERROR serviceapp.amocrm_client Не удалось выполнить поиск контактов в AmoCRM. Статус: 400, Ответ: {"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Filter is not array"}, Параметры запроса: {'page': 1, 'limit': 50, 'filter': '[{"field": "744499", "operator": "EQUALS", "value": "clientlogin1"}]'}
[2024-12-28 23:39:18,860] INFO serviceapp.serializers User with phone=+79990000000 found (id=1), updating data.
[2024-12-28 23:39:18,871] DEBUG serviceapp.amocrm_client Searching contacts with params: {'page': 1, 'limit': 50, 'filter': '[{"field": {"id": "744499"}, "operator": "EQUALS", "value": "clientlogin1"}]'}
[2024-12-28 23:39:19,348] ERROR serviceapp.amocrm_client Не удалось выполнить поиск контактов в AmoCRM. Статус: 400, Ответ: {"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Filter is not array"}, Параметры запроса: {'page': 1, 'limit': 50, 'filter': '[{"field": {"id": "744499"}, "operator": "EQUALS", "value": "clientlogin1"}]'}
[2024-12-28 23:40:36,911] INFO serviceapp.serializers User with phone=+79990000000 found (id=1), updating data.
[2024-12-28 23:40:36,914] DEBUG serviceapp.amocrm_client Searching contacts with params: {'page': 1, 'limit': 50, 'filter': '{"logic": "or", "conditions": [{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]}'}
[2024-12-28 23:40:37,384] ERROR serviceapp.amocrm_client Не удалось выполнить поиск контактов в AmoCRM. Статус: 400, Ответ: {"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Filter is not array"}, Параметры запроса: {'page': 1, 'limit': 50, 'filter': '{"logic": "or", "conditions": [{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]}'}
[2024-12-28 23:40:38,856] INFO serviceapp.serializers User with phone=+79990000000 found (id=1), updating data.
[2024-12-28 23:40:38,867] DEBUG serviceapp.amocrm_client Searching contacts with params: {'page': 1, 'limit': 50, 'filter': '{"logic": "or", "conditions": [{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]}'}
[2024-12-28 23:40:39,320] ERROR serviceapp.amocrm_client Не удалось выполнить поиск контактов в AmoCRM. Статус: 400, Ответ: {"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Filter is not array"}, Параметры запроса: {'page': 1, 'limit': 50, 'filter': '{"logic": "or", "conditions": [{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]}'}
[2024-12-28 23:41:35,166] INFO serviceapp.serializers User with phone=+79990000000 found (id=1), updating data.
[2024-12-28 23:41:35,169] DEBUG serviceapp.amocrm_client Searching contacts with params: {'page': 1, 'limit': 50, 'filter': '{"conditions": [{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]}'}
[2024-12-28 23:41:35,658] ERROR serviceapp.amocrm_client Не удалось выполнить поиск контактов в AmoCRM. Статус: 400, Ответ: {"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Filter is not array"}, Параметры запроса: {'page': 1, 'limit': 50, 'filter': '{"conditions": [{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]}'}
[2024-12-28 23:44:08,745] INFO serviceapp.serializers User with phone=+79990000000 found (id=1), updating data.
[2024-12-28 23:44:08,748] DEBUG serviceapp.amocrm_client Searching contacts with params: {'page': 1, 'limit': 50, 'filter': '[{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]'}
[2024-12-28 23:44:09,221] ERROR serviceapp.amocrm_client Не удалось выполнить поиск контактов в AmoCRM. Статус: 400, Ответ: {"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Filter is not array"}, Параметры запроса: {'page': 1, 'limit': 50, 'filter': '[{"field": {"id": 744499}, "operator": "EQUALS", "value": "clientlogin1"}]'}
[2024-12-28 23:47:15,705] INFO serviceapp.serializers User with phone=+79990000000 found (id=1), updating data.
[2024-12-28 23:47:15,715] DEBUG serviceapp.amocrm_client Creating contact in AmoCRM. URL: https://servicecentru.amocrm.ru/api/v4/contacts, Data: {'name': 'Тестовый контакт 4', 'custom_fields_values': [{'field_code': 'PHONE', 'values': [{'value': '+79990000000', 'enum_code': 'WORK'}]}, {'field_id': 744499, 'values': [{'value': 'clientlogin1'}]}]}
[2024-12-28 23:47:16,304] INFO serviceapp.amocrm_client Contact created in AmoCRM with ID: 29445321
[2024-12-28 23:47:16,305] INFO serviceapp.serializers Создан новый контакт в AmoCRM (id=29445321) для пользователя id=1
[2025-01-07 21:47:54,878] ERROR serviceapp.views Unexpected error: 'ServiceRequest' object has no attribute 'amocrm_lead_id'
[2025-01-07 21:49:37,332] ERROR serviceapp.views Unexpected error: 'AmoCRMClient' object has no attribute 'headers'
[2025-01-07 21:50:30,077] ERROR serviceapp.views Unexpected error: 'AmoCRMClient' object has no attribute 'headers'
[2025-01-07 21:54:58,642] ERROR serviceapp.views Unexpected error: 'AmoCRMClient' object has no attribute 'headers'
[2025-01-07 21:56:35,260] ERROR serviceapp.amocrm_client Failed to fetch lead 24761877: {"title":"Not Found","type":"https://httpstatus.es/404","status":404,"detail":"Cannot GET https://servicecentru.amocrm.ru/api/v4/leads/24761877!"}
[2025-01-07 21:56:35,513] ERROR serviceapp.views Unexpected error: 404 Client Error: Not Found for url: https://servicecentru.amocrm.ru/api/v4/api/v4/leads/24761877
[2025-01-07 21:58:30,394] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-07 21:58:30,394] INFO serviceapp.amocrm_client Контакт 29451439 успешно прикреплён к лиду 24761877
[2025-01-07 23:27:04,684] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-07 23:27:05,714] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-07 23:27:05,714] INFO serviceapp.amocrm_client Контакт 29451439 успешно прикреплён к лиду 24761877
[2025-01-07 23:41:13,860] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-07 23:41:14,960] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-07 23:41:14,961] INFO serviceapp.amocrm_client Контакт 29451439 успешно прикреплён к лиду 24761877
[2025-01-07 23:58:55,788] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-07 23:58:56,906] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-07 23:58:56,907] INFO serviceapp.amocrm_client Контакт 29451439 успешно прикреплён к лиду 24761877
[2025-01-10 23:47:28,388] ERROR serviceapp.amocrm_client Failed to update lead 24761877: {"validation-errors":[{"request_id":"0","errors":[{"code":"NotSupportedChoice","path":"custom_fields_values.2.field_id","detail":"The value you selected is not a valid choice."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}
[2025-01-10 23:47:28,634] ERROR serviceapp.views Unexpected error: 400 Client Error: Bad Request for url: https://servicecentru.amocrm.ru/api/v4/leads/24761877
[2025-01-10 23:48:23,955] ERROR serviceapp.amocrm_client Failed to update lead 24761877: {"validation-errors":[{"request_id":"0","errors":[{"code":"NotSupportedChoice","path":"custom_fields_values.2.field_id","detail":"The value you selected is not a valid choice."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}
[2025-01-10 23:48:24,201] ERROR serviceapp.views Unexpected error: 400 Client Error: Bad Request for url: https://servicecentru.amocrm.ru/api/v4/leads/24761877
[2025-01-10 23:49:22,717] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-10 23:49:23,760] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-10 23:49:23,760] INFO serviceapp.amocrm_client Контакт 29451439 успешно прикреплён к лиду 24761877
[2025-01-11 18:50:01,060] ERROR serviceapp.views Unexpected error in finish_request: column serviceapp_servicerequest.warranty does not exist
LINE 1: ...", "serviceapp_servicerequest"."amo_status_code", "serviceap...
                                                             ^
[2025-01-11 18:56:41,143] ERROR serviceapp.views Unexpected error in finish_request: column serviceapp_servicerequest.warranty does not exist
LINE 1: ...", "serviceapp_servicerequest"."amo_status_code", "serviceap...
                                                             ^
[2025-01-11 19:02:20,471] ERROR serviceapp.amocrm_client Failed to update lead 24761877: {"validation-errors":[{"request_id":"0","errors":[{"code":"InvalidType","path":"price","detail":"This value should be of type int."}]}],"title":"Bad Request","type":"https://httpstatus.es/400","status":400,"detail":"Request validation failed"}
[2025-01-11 19:02:20,721] ERROR serviceapp.views Unexpected error in finish_request: 400 Client Error: Bad Request for url: https://servicecentru.amocrm.ru/api/v4/leads/24761877
[2025-01-11 19:04:49,301] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-11 19:14:19,888] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-01-11 19:16:10,934] INFO serviceapp.amocrm_client Lead 24761877 updated successfully
[2025-02-05 23:50:44,448] INFO serviceapp.serializers No user with phone=+77057190585, creating new.
[2025-02-05 23:50:45,232] DEBUG serviceapp.amocrm_client Creating contact in AmoCRM. URL: https://servicecentru.amocrm.ru/api/v4/contacts, Data: {'name': 'Тестов Тест Тестович', 'custom_fields_values': [{'field_code': 'PHONE', 'values': [{'value': '+77057190585', 'enum_code': 'WORK'}]}, {'field_id': 744499, 'values': [{'value': '517608026'}]}, {'field_id': 744523, 'values': [{'value': 'Client'}]}, {'field_id': 744509, 'values': [{'value': 0}]}, {'field_id': 744521, 'values': [{'value': 5}]}, {'field_id': 744219, 'values': [{'value': 'Москва'}]}]}
[2025-02-05 23:50:47,000] ERROR serviceapp.amocrm_client Failed to create contact in AmoCRM. Status code: 401, Response text: {"title":"Unauthorized","type":"https://httpstatus.es/401","status":401,"detail":"Неверный логин или пароль"}, Tried data: {'name': 'Тестов Тест Тестович', 'custom_fields_values': [{'field_code': 'PHONE', 'values': [{'value': '+77057190585', 'enum_code': 'WORK'}]}, {'field_id': 744499, 'values': [{'value': '517608026'}]}, {'field_id': 744523, 'values': [{'value': 'Client'}]}, {'field_id': 744509, 'values': [{'value': 0}]}, {'field_id': 744521, 'values': [{'value': 5}]}, {'field_id': 744219, 'values': [{'value': 'Москва'}]}]}
[2025-02-05 23:50:47,001] ERROR serviceapp.serializers Ошибка при создании контакта в AmoCRM: 401 Client Error: Unauthorized for url: https://servicecentru.amocrm.ru/api/v4/contacts
Traceback (most recent call last):
  File "C:\Users\akbar\OneDrive\Рабочий стол\Home Service Bot\myproject\serviceapp\serializers.py", line 247, in create
    created_contact = amo_client.create_contact(contact_data)
  File "C:\Users\akbar\OneDrive\Рабочий стол\Home Service Bot\myproject\serviceapp\amocrm_client.py", line 59, in create_contact
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\akbar\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://servicecentru.amocrm.ru/api/v4/contacts
[2025-02-05 23:52:46,659] INFO serviceapp.serializers No user with phone=+77057190585, creating new.
[2025-02-05 23:52:47,416] DEBUG serviceapp.amocrm_client Creating contact in AmoCRM. URL: https://servicecentru.amocrm.ru/api/v4/contacts, Data: {'name': 'Тестов Тест Тестович', 'custom_fields_values': [{'field_code': 'PHONE', 'values': [{'value': '+77057190585', 'enum_code': 'WORK'}]}, {'field_id': 744499, 'values': [{'value': '517608026'}]}, {'field_id': 744523, 'values': [{'value': 'Client'}]}, {'field_id': 744509, 'values': [{'value': 0}]}, {'field_id': 744521, 'values': [{'value': 5}]}, {'field_id': 744219, 'values': [{'value': 'Москва'}]}]}
[2025-02-05 23:52:47,896] ERROR serviceapp.amocrm_client Failed to create contact in AmoCRM. Status code: 401, Response text: {"title":"Unauthorized","type":"https://httpstatus.es/401","status":401,"detail":"Неверный логин или пароль"}, Tried data: {'name': 'Тестов Тест Тестович', 'custom_fields_values': [{'field_code': 'PHONE', 'values': [{'value': '+77057190585', 'enum_code': 'WORK'}]}, {'field_id': 744499, 'values': [{'value': '517608026'}]}, {'field_id': 744523, 'values': [{'value': 'Client'}]}, {'field_id': 744509, 'values': [{'value': 0}]}, {'field_id': 744521, 'values': [{'value': 5}]}, {'field_id': 744219, 'values': [{'value': 'Москва'}]}]}
[2025-02-05 23:52:47,897] ERROR serviceapp.serializers Ошибка при создании контакта в AmoCRM: 401 Client Error: Unauthorized for url: https://servicecentru.amocrm.ru/api/v4/contacts
Traceback (most recent call last):
  File "C:\Users\akbar\OneDrive\Рабочий стол\Home Service Bot\myproject\serviceapp\serializers.py", line 247, in create
    created_contact = amo_client.create_contact(contact_data)
  File "C:\Users\akbar\OneDrive\Рабочий стол\Home Service Bot\myproject\serviceapp\amocrm_client.py", line 59, in create_contact
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\akbar\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://servicecentru.amocrm.ru/api/v4/contacts
[2025-02-05 23:55:19,974] INFO serviceapp.serializers No user with phone=+77057190585, creating new.
[2025-02-05 23:55:20,724] DEBUG serviceapp.amocrm_client Creating contact in AmoCRM. URL: https://servicecentru.amocrm.ru/api/v4/contacts, Data: {'name': 'Тестов Тест Тестович', 'custom_fields_values': [{'field_code': 'PHONE', 'values': [{'value': '+77057190585', 'enum_code': 'WORK'}]}, {'field_id': 744499, 'values': [{'value': '517608026'}]}, {'field_id': 744523, 'values': [{'value': 'Client'}]}, {'field_id': 744509, 'values': [{'value': 0}]}, {'field_id': 744521, 'values': [{'value': 5}]}, {'field_id': 744219, 'values': [{'value': 'Москва'}]}]}
[2025-02-05 23:55:21,709] INFO serviceapp.amocrm_client Contact created in AmoCRM with ID: 29504614
[2025-02-05 23:55:21,959] INFO serviceapp.serializers Created contact in AmoCRM (id=29504614) for user_id=3
